name: bmi_calculator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  syncfusion_flutter_gauges: ^27.2.5

dev_dependencies:
  flutter_launcher_icons: ^0.13.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  rename_app: ^1.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
